# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cliente.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'cliente.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcliente.proto\"i\n\x07\x43liente\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\x0c\n\x04mail\x18\x03 \x01(\t\x12\x10\n\x08telefono\x18\x04 \x01(\t\x12\x0f\n\x07tipo_id\x18\x05 \x01(\x05\x12\x11\n\tgenero_id\x18\x06 \x01(\x05\"\x1c\n\x0e\x43lienteRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x32=\n\x0e\x43lienteService\x12+\n\x0eObtenerCliente\x12\x0f.ClienteRequest\x1a\x08.Clienteb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cliente_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLIENTE']._serialized_start=17
  _globals['_CLIENTE']._serialized_end=122
  _globals['_CLIENTEREQUEST']._serialized_start=124
  _globals['_CLIENTEREQUEST']._serialized_end=152
  _globals['_CLIENTESERVICE']._serialized_start=154
  _globals['_CLIENTESERVICE']._serialized_end=215
# @@protoc_insertion_point(module_scope)
